# AMCL Parameters for Omni-Directional Holonomic Robot
odom_frame_id: odom
base_frame_id: base_link
global_frame_id: map
transform_tolerance: 0.1
min_particles: 100
max_particles: 500
update_min_d: 0.1
update_min_a: 0.1
resample_interval: 1
gui_publish_rate: 10.0
laser_model_type: likelihood_field
laser_likelihood_max_dist: 3.0
odom_model_type: omni
min_range: 0.3
max_range: 10.0
max_beams: 60
sigma_hit: 0.2
alpha_hit: 0.5
