global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 3.0
  static_map: true

plugins:
  - {name: static, type: "costmap_2d::StaticLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}

static:
  map_topic: /map
  subscribe_to_updates: true

inflation:
  inflation_radius: 0.09
  cost_scaling_factor: 3.25
