footprint: [[-0.27, -0.27], [-0.27, 0.27], [0.27, 0.27], [0.27, -0.27]]  # Robot footprint vertices (in meters)
footprint_padding: 0.1 # Padding around the robot's footprint (in meters)

robot_base_frame: base_link  # Frame representing the robot's base

# Other costmap parameters (obstacle_range, raytrace_range, etc.)
resolution: 0.05  # Costmap resolution (meters per pixel)
obstacle_range: 6  # Maximum range for obstacle insertion (meters)
raytrace_range: 6  # Maximum range for raytracing (meters)
transform_tolerance: 1  # Transform tolerance for map and robot positions (seconds)

# Global and local costmap parameters
global_frame: map
rolling_window: false
track_unknown_space: true
publish_frequency: 3.0
update_frequency: 5.0

plugins:
  - {name: static, type: "costmap_2d::StaticLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}

static:
  map_topic: /map
  subscribe_to_updates: true

inflation:
  inflation_radius: 0.09
  cost_scaling_factor: 3.25