controller_frequency: 20.0
recovery_behaviour_enabled: false
oscillation_distance: 0.5
oscillation_timeout: 20
planner_patience: 20.0
controller_patience: 50.0
recovery_behaviors:
  - {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
  - {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}

# Global Planner Configuration
GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.2
  visualize_potential: true
  use_dijkstra: true
  use_quadratic: false
  use_grid_path: false
  old_navfn_behavior: true
  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 3.0
  publish_potential: true
  planner_window_x: 0.0
  planner_window_y: 0.0
  publish_scale: 100
  planner_costmap_publish_frequency: 10.0

# teb_local_planner_params.yaml
TebLocalPlannerROS:
  odom_topic: odom
  map_frame: odom

  # Trajectory configuration
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: true
  allow_init_with_backwards_motion: false
  max_global_plan_lookahead_dist: 3.0
  global_plan_viapoint_sep: -1
  global_plan_prune_distance: 1
  exact_arc_length: false
  feasibility_check_no_poses: 5
  publish_feedback: true

  # Robot configuration
  max_vel_x: 2.0
  max_vel_x_backwards: 2.0
  max_vel_y: 2.0
  max_vel_theta: 1.0
  acc_lim_x: 10.0
  acc_lim_theta: 4.0
  min_turning_radius: 0.0
  footprint_model: 
    type: "polygon"
    vertices: [[-0.27, -0.27], [-0.27, 0.27], [0.27, 0.27], [0.27, -0.27]]
  # footprint_model:
  # type: "point"

  # Goal tolerance
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: false
  complete_global_plan: true

  # Obstacles
  min_obstacle_dist: 0.5
  inflation_dist: 0.2
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 10
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.1
  obstacle_cost_exponent: 4
  weight_max_vel_x: 2
  weight_max_vel_y: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_y: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1
  weight_optimaltime: 1
  weight_shortest_path: 0
  weight_obstacle: 50
  weight_dynamic_obstacle: 10

  # Homotopy class planner
  enable_homotopy_class_planning: true
  enable_multithreading: true
  simple_exploration: false
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 6
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.4
  visualize_hc_graph: false
